MvcApplication1/Controllers/TagController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcApplication1.Models;

namespace MvcApplication1.Controllers
{
    [Authorize(Roles="root")]
    public class TagController : Controller
    {
        private MyDbContext db = new MyDbContext();

        public ActionResult Index()
        {
            return View(db.Tags.ToList());
        }


        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Tag tag)
        {
            if (ModelState.IsValid)
            {
                db.Tags.Add(tag);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tag);
        }

        public ActionResult Edit(int id = 0)
        {
            Tag tag = db.Tags.Find(id);
            if (tag == null)
            {
                return HttpNotFound();
            }
            return View(tag);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Tag tag)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tag).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tag);
        }

        public ActionResult Delete(int id = 0)
        {
            Tag tag = db.Tags.Find(id);
            if (tag == null)
            {
                return HttpNotFound();
            }
            return View(tag);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tag tag = db.Tags.Find(id);

            foreach (var x in db.Problems.Where(x => x.Tag.ID == id))
            {
                db.Entry(x).Reference(c => c.Tag).CurrentValue = null;
                db.Entry(x).State = EntityState.Modified;
            }

            foreach (var x in db.Contests.Where(x => x.Tag.ID == id))
            {
                db.Entry(x).Reference(c => c.Tag).CurrentValue = null;
                db.Entry(x).State = EntityState.Modified;
            }

            db.Tags.Remove(tag);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MvcApplication1/Views/Tag/Create.cshtml
@model MvcApplication1.Models.Tag

@{
    ViewBag.Title = "新建分类";
}

<h2>新建分类</h2>

@using (Html.BeginForm("Create", "Tag", FormMethod.Post, new { enctype = "multipart/form-data", @class = "col-md-6" })) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div class="form-group">
            <label for="Tag">标签名称</label>
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
    </div>

    <p>
        <input type="submit" value="新建" class="btn btn-success" />
    </p>
}

MvcApplication1/Views/Tag/Delete.cshtml
@model MvcApplication1.Models.Tag

@{
    ViewBag.Title = "删除分类";
}

<h2>删除分类</h2>
<div class="well">
    @Html.DisplayFor(model => model.Name)
</div>
<p>原属于这个分类的题目和比赛将属于(未分类)</p>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="删除" class="btn btn-danger" /> <b>操作不可以撤销！</b>
    </p>
}

MvcApplication1/Views/Tag/Edit.cshtml
@model MvcApplication1.Models.Tag

@{
    ViewBag.Title = "编辑分类";
}

<h2>编辑分类</h2>
@using (Html.BeginForm("Edit", "Tag", FormMethod.Post, new { enctype = "multipart/form-data", @class = "col-md-6" }))
{

    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.ID)
    <div class="form-group">
        <label for="Tag">标签名称</label>
        @Html.EditorFor(model => model.Name)
        @Html.ValidationMessageFor(model => model.Name)
    </div>

    <p>
        <input type="submit" value="保存" class="btn btn-success" />
    </p>
}

MvcApplication1/Views/Tag/Index.cshtml
@model IEnumerable<MvcApplication1.Models.Tag>

@{
    ViewBag.Title = "分类管理";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("新建分类", "Create",null, new { @class = "btn btn-success" })
</p>
<table class="table table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("编辑", "Edit", new { id=item.ID })
            @Html.ActionLink("删除", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>