MvcApplication1/Controllers/ProblemController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.IO.Compression;
using System.Security.Cryptography;
using System.Text;
using MvcApplication1.Models;
using MvcApplication1.FormModels;
using MvcApplication1.Filters;
using Newtonsoft.Json;
using WebMatrix.WebData;
using AutoMapper;

namespace MvcApplication1.Controllers
{
    [Authorize]
    public class ProblemController : Controller
    {
        private MyDbContext db = new MyDbContext();

        [NonAction]
        public void Refresh()
        {
            foreach (var x in db.Contests.AsQueryable().Where( m => m.Public && m.Start < DateTime.Now).ToList() )
            {
                foreach (var p in x.ProbList.AsEnumerable().ToList())
                {
                    p.Public = true;
                    db.Entry(p).State = EntityState.Modified;
                }
                x.Public = false;
                db.SaveChanges();
            }

            foreach (var x in db.Contests.AsQueryable().Where(m => m.PublicData && m.End < DateTime.Now).ToList())
            {
                foreach (var p in x.ProbList.AsEnumerable().ToList())
                {
                    p.PublicData = true;
                    db.Entry(p).State = EntityState.Modified;
                }
                x.PublicData = false;
                db.SaveChanges();
            }

            foreach (var x in db.Contests.AsQueryable().Where(m => m.PublicSolution && m.End < DateTime.Now).ToList())
            {
                foreach (var p in x.ProbList.AsEnumerable().ToList())
                {
                    p.PublicSolution = true;
                    db.Entry(p).State = EntityState.Modified;
                }
                x.PublicSolution = false;
                db.SaveChanges();
            }
        }

        public ActionResult Index(int tag = 0)
        {
            Refresh();

            var tmp = db.Submits.Where(m => m.User.UserId == WebSecurity.CurrentUserId)
                .GroupBy(m => m.Prob.ID)
                .Select(x => x.OrderByDescending(z => z.Time).FirstOrDefault())
                .ToList()
                .ToDictionary(y => y.Prob.ID);
            ViewBag.Record = tmp;
            var query = db.Problems.AsQueryable();
            if (!User.IsInRole("admin"))
                query = query.Where(x => x.Public);
            if (tag != 0)
                query = query.Where(x => x.Tag.ID == tag);
            ViewBag.tagList = HelperFunc.GetTagList(tag);
            return View(query.ToList());
        }

        public ActionResult Details(int id = 0,int c = 0)
        {
            Problem problem = db.Problems.Find(id);
            Contest contest = db.Contests.Find(c);
            ViewBag.c = c;
            ViewBag.ContTitle = contest!=null ? contest.Title : null;
            if (problem == null)
                return HttpNotFound();
            if (c!=0)
            {
                if (contest == null)
                    return View("Error", new HttpException(403, "没有找到比赛。"));
                if (contest.State == ContestState.Before)
                    return View("Error", new HttpException(403, "比赛尚未开始。"));
                if (!contest.UserList.Any(x => x.UserName == User.Identity.Name))
                    return View("Error", new HttpException(403, "您没有参与这场比赛。"));
                ViewBag.ContState = contest.State;
                
                return View(problem);
            }

            if (User.IsInRole("admin") || problem.Public)
                return View(problem);
            return View("Error", new HttpException(403, "题目是隐藏的。请尝试使用管理员账号登陆。"));
        }

        public ActionResult Solution(int id = 0)
        {
            Problem problem = db.Problems.Find(id);
            if (problem == null)
                return HttpNotFound();

            if (User.IsInRole("admin") || problem.PublicSolution)
                return View(problem);
            return View("Error", new HttpException(403, "题解是隐藏的。请尝试使用管理员账号登陆。"));
        }

        [Authorize(Roles="admin")]
        public ActionResult Create()
        {
            ViewBag.tagList = HelperFunc.GetTagList(0, "(未分类)");
            return View(new UploadProblemModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult Create(UploadProblemModel form)
        {
            Mapper.CreateMap<UploadProblemModel,Problem>()
                .ForMember( x => x.Tag , s => s.Ignore());
            var tmp = Mapper.Map<Problem>(form);
            tmp.Tag = db.Tags.Find(form.Tag);
            if (form.File == null || !HelperFunc.ReadConfig(ref tmp, form.File.InputStream))
                ModelState.AddModelError("File","必须选择一个有效的数据文件。");

            if (ModelState.IsValid)
            {
                tmp.CheckSum = HelperFunc.HashFile(form.File.InputStream);
                db.Problems.Add(tmp);
                db.SaveChanges();
                form.File.SaveAs(HelperFunc.GetZipPath(tmp.ID));
                return RedirectToAction("Index");
            }
            ViewBag.tagList = HelperFunc.GetTagList(form.Tag, "(未分类)");
            return View(form);
        }

        [Authorize(Roles = "admin")]
        public ActionResult Edit(int id = 0)
        {
            var problem = db.Problems.Find(id);
            if (problem == null) return HttpNotFound();

            Mapper.CreateMap<Problem,UploadProblemModel>()
                .ForMember(x => x.Tag, s => s.MapFrom(y => y==null?0:y.Tag.ID));
            var tmp = Mapper.Map<UploadProblemModel>(problem);
            ViewBag.tagList = HelperFunc.GetTagList(problem.Tag == null ? 0 : problem.Tag.ID, "(未分类)");
            return View(tmp);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult Edit(UploadProblemModel form,int id = 0)
        {
            var prob = db.Problems.Find(id);
            if (prob == null)
                return HttpNotFound();
            if (form.File != null)
                if(!HelperFunc.ReadConfig(ref prob, form.File.InputStream))
                    ModelState.AddModelError("File", "必须选择一个有效的数据文件。");

            if (ModelState.IsValid)
            {
                prob.Title = form.Title;
                prob.Public = form.Public;
                prob.PublicData = form.PublicData;
                //prob.Tag = db.Tags.Find(form.Tag) ;
                db.Entry(prob).Reference(m => m.Tag).CurrentValue = db.Tags.Find(form.Tag);
                if (form.File != null)
                {
                    prob.CheckSum = HelperFunc.HashFile(form.File.InputStream);
                    System.IO.File.Delete(HelperFunc.GetZipPath(id));
                    form.File.SaveAs(HelperFunc.GetZipPath(id));
                }
                db.Entry(prob).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            ViewBag.tagList = HelperFunc.GetTagList(form.Tag, "(未分类)");
            return View(form);
        }

        [Authorize(Roles = "admin")]
        public ActionResult Delete(int id = 0)
        {
            Problem problem = db.Problems.Find(id);
            if (problem == null)
            {
                return HttpNotFound();
            }
            return View(problem);
        }

        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "admin")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Problem problem = db.Problems.Find(id);
            db.Problems.Remove(problem);
            db.SaveChanges();
            System.IO.File.Delete(HelperFunc.GetZipPath(id));
            return RedirectToAction("Index");
        }

        public ActionResult Downland(int id)
        {
            Problem problem = db.Problems.Find(id);
            if (problem == null)
                return HttpNotFound();
            if (problem.PublicData || User.IsInRole("admin"))
                return File(HelperFunc.GetZipPath(id), "application/zip", id.ToString() + ".zip");
            return View("Error", new HttpException(403, "没有权限下载数据"));
        }

        public ActionResult file(int id,string fn)
        {
            Problem problem = db.Problems.Find(id);
            if (problem == null)
                return HttpNotFound();
            if (problem.Public || User.IsInRole("admin"))
            {
                var zip = ZipFile.OpenRead(HelperFunc.GetZipPath(id));
                var stream =  HelperFunc.ReadZipStream(zip,"file/"+fn);
                if (stream== null)
                    return HttpNotFound();
                return File(stream, "application/octet-stream",fn);

            }
            return View("Error", new HttpException(403, "题目是隐藏的。请尝试使用管理员账号登陆。"));
        }


        [Authorize(Roles = "admin")]
        public ActionResult EditHTML(int id = 0)
        {
            var problem = db.Problems.Find(id);
            if (problem == null)
                return HttpNotFound();

            return View(problem);
        }

        [HttpPost, ActionName("EditHTML")]
        [Authorize(Roles = "admin")]
        [ValidateInput(false)]
        public ActionResult EditHTMLPost(int id = 0)
        {
            var problem = db.Problems.Find(id);
            if (problem == null)
                return HttpNotFound();
            problem.Description = Request.Unvalidated.Form.Get("Description");
            problem.Solution = Request.Unvalidated.Form.Get("Solution");
            db.Entry(problem).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Details");
        }

        protected override void Dispose(bool disposing)
        {

MvcApplication1/Controllers/SubmitController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMatrix.WebData;
using MvcApplication1.Models;
using MvcApplication1.FormModels;
using Newtonsoft.Json;
using AutoMapper;
using MvcApplication1.Filters;


namespace MvcApplication1.Controllers
{
    [Authorize]
    public class SubmitController : Controller
    {
        private MyDbContext db = new MyDbContext();

        [NonAction]
        public void SetUpdate(Contest c)
        {
            if (c != null)
            {
                c.Update = true;
                db.Entry(c).State = EntityState.Modified;
            }
        }

        public IQueryable<Submit> Search(IQueryable<Submit> query, SubmitSearchModel search)
        {
            if (search.S != null)
                query = query.Where(m => m.ID == search.S);
            if (search.C != null)
                query = query.Where(m => m.Belog.ID == search.C);
            if (search.P != null)
                query = query.Where(m => m.Prob.ID == search.P);

            if (!String.IsNullOrWhiteSpace(search.U))
                query = query.Where(m => m.User.UserName == search.U);
            if (search.State != null)
                query = query.Where(m => m.State == search.State);
            return query;
        }

        public bool isSearch(SubmitSearchModel search)
        {
            return search.P != null || search.S != null || search.C != null || !String.IsNullOrWhiteSpace(search.U) || search.State != null;
        }

        public List<SelectListItem> GetSelectListItem(SubmitSearchModel search)
        {
            var StateList = new List<SelectListItem>();
            StateList.Add(new SelectListItem{Text = "(状态)",Value = "",Selected = search.State == null});
            foreach (var x in Enum.GetNames(typeof(SubmitState)))
            {
                StateList.Add(new SelectListItem { Text = x, Value = x, Selected = x == search.State.ToString() });
            }
            return StateList;
        }


        public ActionResult Index(SubmitSearchModel search)
        {
            ViewBag.StateList = GetSelectListItem(search);
            var query = Search(db.Submits,search);
            ViewBag.Res =Pagination( query.OrderByDescending(m => m.Time)).ToList();
            ViewBag.isSearch = isSearch(search);
            return View(search);
        }

        [HttpPost, ActionName("Index")]
        [ValidateAntiForgeryToken]
        public ActionResult IndexPost(SubmitSearchModel search) 
        {
            var query = Search(db.Submits,search);
            if (Request.Form["Rejudge"] == "REJDGE")
            {
                foreach (var x in query.ToList())
                {
                    x.State = SubmitState.Waiting;
                    SetUpdate(x.Belog);
                    db.Entry(x).State = EntityState.Modified;
                }
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id = 0)
        {
            Submit submit = db.Submits.Find(id);
            if (submit == null)
            {
                return HttpNotFound();
            }
            ViewBag.Res = JsonConvert.DeserializeObject(
                string.IsNullOrEmpty(submit.Result) ? "[]" : submit.Result
            );
            return View(submit);
        }

        public ActionResult Create(int id = 0,int c = 0)
        {
            var tmp = db.Problems.Find(id);
            if (tmp == null)
                return HttpNotFound();
            ViewBag.ProbTitle = tmp.Title;
            if (c!=0)
            {
                var contest = db.Contests.Find(c);
                if (contest == null)
                    return View("Error", new HttpException(403, "没有找到比赛"));
                if (contest.State != ContestState.Running)
                    return View("Error", new HttpException(403, "比赛已经结束或尚未开始。"));
                if (!contest.UserList.Any(x => x.UserName == User.Identity.Name))
                    return View("Error", new HttpException(403, "您没有参与这场比赛。"));
                ViewBag.ContTitle = contest.Title;
            }

            return View(new SubmitModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create(SubmitModel submit,int id = 0,int c = 0)
        {
            var prob = db.Problems.Find(id);
            if (prob == null)
                return HttpNotFound();
            var tmp = CreateSubmit(prob, submit);
            if (c != 0)
            {
                var tc = db.Contests.Find(c);
                tmp.Belog = tc;
                SetUpdate(tc);
            }
            if (ModelState.IsValid)
            {
                db.Submits.Add(tmp);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(submit);
        }

        public ActionResult Delete(int id = 0)
        {
            Submit submit = db.Submits.Find(id);
            if (submit == null)
            {
                return HttpNotFound();
            }
            return View(submit);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Submit submit = db.Submits.Find(id);
            SetUpdate(submit.Belog);
            db.Submits.Remove(submit);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        #region 帮助程序

        [NonAction]
        public Submit CreateSubmit(Problem prob,SubmitModel x)
        {
            var ret = new Submit();
            ret.User = db.UserProfiles.Find(WebSecurity.CurrentUserId);
            ret.Prob = prob;
            ret.Lang = x.Lang;
            ret.Source = x.Src;
            return ret;
        }

        [NonAction]
        public IQueryable<Submit> Pagination(IQueryable<Submit> tmp)
        {
            int PAGE_SIZE = 30;
            int page = 1, totpage = (tmp.Count() + PAGE_SIZE - 1) / PAGE_SIZE; 
            if (Request.QueryString["page"] != null)
            {
                Int32.TryParse(Request.QueryString["page"], out page);
            }
            ViewBag.page = page; ViewBag.totpage = totpage;  //数据传递给ViewBag
            return tmp.Skip((page - 1) * PAGE_SIZE).Take(PAGE_SIZE);
        }

        #endregion
    }
}

MvcApplication1/Views/Contest/Create.cshtml
@model MvcApplication1.FormModels.ContestFormModel

@{
    ViewBag.Title = "新建比赛";
}

<h2>新建比赛</h2>

@using (Html.BeginForm()) {
    <div class="col-md-6">
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

        @Html.EditorForModel()
        <p>
            <input type="submit" value="创建" class="btn btn-success" />
        </p>
    </div>
}

MvcApplication1/Views/Contest/Delete.cshtml
@model MvcApplication1.Models.Contest

@{
    ViewBag.Title = "删除比赛";
}

<h2>确认删除这场比赛？</h2>

<div class="well">
   ( @Html.DisplayFor(model => model.ID) ) 
    @Html.DisplayFor(model => model.Title)
</div>
<b>所有比赛中的提交会保留，但是不再属于任何比赛。</b>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="删除" class="btn btn-danger"/> <b>操作不可以撤销！</b>
    </p>
}

MvcApplication1/Views/Contest/Details.cshtml
@model MvcApplication1.Models.Contest

@{
    ViewBag.Title = "比赛题目列表";
}

<h2>@Html.DisplayFor(model => model.Title)</h2>
        
<span>比赛时间 @Html.DisplayFor(model => model.Start) ~ @Html.DisplayFor(model => model.End)</span> 

<table class="table">
    <tr>
        <th>题号</th>
        <th>题目名</th>
        <th>操作</th>
    </tr>
    @foreach(var i in Model.ProbList)
    {
        <tr>
            <td>@i.ID</td>
            <td>@i.Title</td>
            <td>@Html.ActionLink("进入", "Details", "Problem", new { id = @i.ID , c = Model.ID }, new { })</td>
        </tr>
    }
</table>  

MvcApplication1/Views/Contest/Edit.cshtml
@model MvcApplication1.FormModels.ContestFormModel

@{
    ViewBag.Title = "编辑比赛";
}

<h2>编辑比赛</h2>

@using (Html.BeginForm()) {
    <div class="col-md-6">
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    @Html.EditorForModel()
        <p>
            <input type="submit" value="保存" class="btn btn-success" />
        </p>
    </div>
}

MvcApplication1/Views/Contest/Index.cshtml
@model IEnumerable<MvcApplication1.Models.Contest>
@using MvcApplication1.Models
@{
    ViewBag.Title = "比赛列表";
    bool isRoot = User.IsInRole("admin");
}

<h2>比赛列表</h2>
@if (isRoot)
{
    @Html.ActionLink("新建比赛", "Create",null, new { @class = "btn btn-success" })
}

@Html.Partial("_TagSelect")

<table class="table table-striped">
    <tr>
        <th>#</th>
        <th>比赛名称</th>
        <th>比赛时间</th>
        <th>状态</th>
        <th></th>
    </tr>
    @foreach (var i in Model)
    {
        <tr>
            <td>@i.ID</td>
            <td>
                @i.Title
                @if (i.Tag != null)
                {
                    <span class="label label-info">@i.Tag.Name</span>
                }
            </td>
            <td>@i.Start ~ @i.End</td>
            <td>@i.State</td>
            <td style="padding:3px">
                <div class="btn-group"  style="float:right;">
                @if (i.State != ContestState.Before || isRoot)
                {
                    @Html.ActionLink("进入","Details",new { id =i.ID },new {@class="btn btn-default"})
                    @Html.ActionLink("排名","Rank",new { id =i.ID },new {@class="btn btn-default"})
                }
                @if (isRoot)
                {
                    @Html.ActionLink("编辑","Edit",new { id =i.ID },new {@class="btn btn-default"})
                    @Html.ActionLink("删除","Delete",new { id =i.ID },new {@class="btn btn-danger"})
                }
                </div>
            </td>
        </tr>
    }
</table>

MvcApplication1/Views/Contest/Rank.cshtml
@model List<MvcApplication1.FormModels.JsonContestReslut>

@{
    ViewBag.Title = ViewBag.CTitle + " - 比赛排名";
}

<h2>@ViewBag.CTitle - 比赛排名</h2>
@Html.ActionLink("导出", "Rank", new { @id = ViewBag.C, type = "csv", }, new { @class = "btn btn-default" })
<p class="help-block">由于Excal不能直接打开UTF-8编码的CSV文件，请使用文本编辑器转换编码。 </p>
<table class="table table-striped">
    <tr>
        <th>用户名</th>
        @foreach(var x in ViewBag.prob)
        {
            <th>@x.Title</th>
        }
        <th>总分</th>
    </tr>
@foreach (var item in Model) {
    <tr>
        <td>@item.UserName</td>
        @for ( int i=0;i< item.Details.Count;++i)
        {
            <td>@Html.ActionLink(item.Details[i],"Index","Submit",new { P = ViewBag.prob[i].ID , U = item.UserName ,C = ViewBag.C},null)</td>
        }
        <td>@item.Src</td>
    </tr>
}

</table>